### ISSUE TITLE
Frontend > Refactor > Corrigir o "Confirmar Senha" ao adicionar o usuário.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-web#4]
# OVERVIEW 
- Nos models de configurar e adicionar novo usuário, existem dois campos para alterar a senha, um de "senha" e outro de "confirmar senha". Acontece que o campo de "confirmar senha" não está sendo utilizado e o sistema autoriza a mudança da senha independente da compatibilidade das entradas.

# TASK
- [ ] Corrigir a verificação dos campos, antes de submeter a requisição;

# COMMENTS
- O campo senha também não é verificado na hora de criar um usuário, o sistema permite a criação se necessariamente preencher o campo de senha.

**Comment by FLuiz22** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/new/iss%234

**Comment by ManoMax** [comment]
# COMMENT

- A atualização do arquivo package.json foi removida para que o PR fosse aceito.
