### ISSUE TITLE
Frontend > Feature > Adicionar opção de "Logoff".

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-web#5]
# OVERVIEW 
- Após realizar o Login, a única maneira de realizar o Logoff está sendo através da limpeza de cookies.

# TASK
- [ ] Adicionar um botão de Logoff ao sistema;

**Comment by maahog** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/new/iss%235
