### ISSUE TITLE
Frontend > Refactor > Adicionar ocultação de input nos campos de "Inserir Senha" na página de Login e de Cadastro.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-web#7]
# OVERVIEW 
- Diferentemente da página de adicionar usuário, o ambiente de Login e de Cadastro possuem campos de preenchimento de senha sem um devida ocultação de caracteres.

# TASK
- [x] Adicionar ocultação de caracteres na página de cadastro;
- [x] Adicionar ocultação de caracteres na página de login;

**Comment by matheusvictoor** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/12
